### ISSUE TITLE
Bug at line 531 in the node-binance.api.js

### ISSUE THREAD

**Issue by markwienands** [binance-exchange/node-binance-api#35] opened 2018-01-10 12:55 UTC
signedRequest(base+'v3/myTrades', {symbol:symbol, ...options}

is the '...' necessary?

**Comment by janderson215** [comment] 2018-01-10 21:20
I'm having the same issue. I was thinking that I had an issue transpiling the spread operator and my settings were wrong. I'm banging my head against a wall (figuratively) trying to determine the root cause.

**Comment by jaggedsoft** [comment] 2018-01-10 22:06
This breaking change has been fixed in the latest release. I will cut a new release right now

**Comment by jaggedsoft** [comment] 2018-01-10 22:07
Electron doesn't support ES6 natively. I am not sure why. The spread operator has been supported for years now.

**Comment by jaggedsoft** [comment] 2018-01-10 22:15
You can update now. `v0.3.5` is live

**Closed by jaggedsoft** 2018-01-10 22:15 UTC
