### ISSUE TITLE
stop limit for buy

### ISSUE THREAD

**Issue by iBasit** [binance-exchange/node-binance-api#25] opened 2018-01-06 04:47 UTC
In the documentation it only shows stop loss example for sell which is

`binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice});`

I'm assuming its same for buy, is that correct?

`binance.buy("ETHBTC", quantity, price, {stopPrice: stopPrice});`

also, another question, if I use `binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice});` to create stop loss order, would it return order it?  or do I have to call another method to retrieve order it?

**Comment by jaggedsoft** [comment] 2018-01-06 05:33
Yes that is how it's supposed to work

`sell: function(symbol, quantity, price, flags = {}, callback = false)`
The 5th parameter is a callback function that will return the JSON response

Unfortunately stop orders mysteriously stopped working the other day and I haven't had the time to figure out exactly why this is happening

**Comment by gravemaker** [comment] 2018-01-06 14:49
You should change node-binance-api.js line 97 to include the price in any kind of *LIMIT* order.
-		if ( opt.type == "LIMIT" ) {
+              if ( opt.type.includes("LIMIT") ) {
Therefore you can call the function with:
binance.sell("ETHBTC", quantity, price, {type: "STOP_LOSS_LIMIT", stopPrice: stopPrice});

**Comment by jaggedsoft** [comment] 2018-01-07 21:22
Thank you for your suggestions
These were all addressed in https://github.com/jaggedsoft/node-binance-api/commit/000ddec6c4ad20e531086442271b485c2febc446 and commited in release `v0.3.1`

**Closed by jaggedsoft** 2018-01-07 21:22 UTC

**Comment by iBasit** [comment] 2018-01-08 05:56
> Unfortunately stop orders mysteriously stopped working the other day and I haven't had the time to figure out exactly why this is happening

is it safe to say, that it is working now?

**Comment by jaggedsoft** [comment] 2018-01-08 05:58
Yes just make sure you are on the latest version
And then you have to tell it what type of stop loss you want


#### Placing a STOP LOSS order
```javascript
// When the stop is reached, a stop order becomes a market order
// Note: You must also pass one of these type parameters:
// STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT
let type = "STOP_LOSS";
let quantity = 1;
let price = 0.069;
let stopPrice = 0.068;
binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice, type: type});
```

**Comment by iBasit** [comment] 2018-01-08 05:59
Thank you, is there any documentation link for these parameters? So I can and also others can understand what they mean.

**Comment by jaggedsoft** [comment] 2018-01-08 06:01
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade scroll down to "type"

![image](https://user-images.githubusercontent.com/4283360/34660321-3df809ba-f3f6-11e7-9721-db71459be366.png)
![image](https://user-images.githubusercontent.com/4283360/34660328-50eb13c8-f3f6-11e7-9b75-db0db69d1150.png)

**Comment by jemhoward** [comment] 2018-05-17 11:49
I don't see that this works as intended. When using the parameters as

```
// STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT
let type = "STOP_LOSS";
let quantity = 1000;
let price = 0.00000100;
let stopPrice = 0.00000100;
binance.sell("BCNBTC", quantity, price, {stopPrice: stopPrice, type: type});
```
I get the output:

`[ 'SELL(BCNBTC,1000,0.000001) ', {} ]`

No order is placed. If I instead use STOP_LOSS_LIMIT the order is created as expected. This leads me to think STOP_LOSS is not fully implemented in the binance api and only limit orders are successful. 

Please can you clarify.

**Comment by jaggedsoft** [comment] 2018-05-17 17:01
@jemhoward 

Yes I believe you are correct. STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT appear to be the only order types working. I think those are the only types you can set from within the binance official webpage
![image](https://user-images.githubusercontent.com/4283360/40192433-37662af4-59b9-11e8-8452-0abf342d6ae2.png)

**Comment by jemhoward** [comment] 2018-05-17 17:47
Thanks @jaggedsoft, let's hope they implement that for use some time soon and thanks for all your work with binance api and node.js
