### ISSUE TITLE
market buy order throwing error in v0.3.7

### ISSUE THREAD

**Issue by adityamertia** [binance-exchange/node-binance-api#42] opened 2018-01-12 08:46 UTC
Hi,

On v0.3.7 i see below error on market order. market order has nothing to do with price?

BUY(LTCETH,0.01,0) { code: -1013, msg: 'Invalid price.' }

Thanks

**Comment by janderson215** [comment] 2018-01-13 02:55
Ah! I'm having the issue in 0.3.6 as well. Downgrading to 0.3.5 for the time being.

I looked through the code and determined that the issue is somewhere in lines 95-109 and 428, 429. Looks like price is being added to the `data` object and that is being added to the url path on the Object.keys(data) iterator. The `type` is `'LIMIT'`and the `price` is `0` on the data object for marketBuy calls.

Sorry, I don't have time to fix that and make a PR at the moment, but I will gladly do that if not done in the morning.

**Comment by adityamertia** [comment] 2018-01-13 05:12
Yes indeed it exists on 0.3.6. I was wondering why there are so many breaking changes in last few days. Isn't there proper testing that the builds go through?

**Comment by jaggedsoft** [comment] 2018-01-13 05:58
Because I have been away on business this week and the commits have been provided by the community

**Comment by janderson215** [comment] 2018-01-13 06:44
@jaggedsoft dude, you have been killing it, though. I was digging pretty deep into the code base and I’m thoroughly impressed with what you’ve put together. I was able to fix my problems (though they were cascading) within an hour even though my initial assessment was that it would have to take until the next day. Thanks for making is so easily parseable and maintainable!

**Comment by jaggedsoft** [comment] 2018-01-13 10:51
Resolved in `v0.3.8` https://github.com/jaggedsoft/node-binance-api/commit/8bf3cde02379e20ba085d9460d9158487515d8d7

**Closed by jaggedsoft** 2018-01-13 10:51 UTC
Labels: bug
